import DS from "ember-data";

var Produit = DS.Model.extend({
  photo_url: DS.attr('string'),
  marque: DS.attr('string'),
  variete: DS.attr('string'),
  denomination: DS.attr('string'),
  description: DS.attr('string'),
  categorie: DS.attr('string'),
  origine_macro: DS.attr('string'),
  echelle: DS.attr('string'),
  origine_semis: DS.attr('string'),
  conditionnement: DS.attr('number'),
  unite_conditionnement: DS.attr('string'),
  unite_nutrition: DS.attr('string'),
  prix_conditionnement: DS.attr('number'),
  prix_global: DS.attr('number'),
  prix_producteur: DS.attr('number'),
  unite_globale: DS.attr('string'),
  prix_portion: DS.attr('number'),
  energie_portion: DS.attr('number'),
  nombre_portions: DS.attr('number'),
  poids_portion: function(){
    return Math.round(this.get('conditionnement') * 100 / this.get('nombre_portions')) / 100;
  }.property('nombre_portions',
    'conditionnement'),
  unite_portion: DS.attr('string'),
  circuit: DS.attr('string'),
  distance: DS.attr('number'),
  transports: DS.attr('string'),
  modes_transports: function(){
      return this.get("transports").split(",");
  }.property('transports'),
  producteur: DS.attr('string'),
  mode_recolte: DS.attr('string'),
  mode_culture: DS.attr('string'),
  mode_culture_img: function(){
      return "assets/img/" + this.get("mode_culture") + ".png";
  }.property("mode_culture"),
  distributeur: DS.attr('string'),
  grossiste: DS.attr('string'),
  lieu_production: DS.attr('string'),
  lieu_achat: DS.attr('string'),
  lieu_vente: DS.attr('string'),
  date_semis: DS.attr('string'),
  date_recolte: DS.attr('string'),
  date_achat: DS.attr('string'),
  date_mise_en_vente: DS.attr('string'),
  date_limite_conso: DS.attr('string'),
  transparence: DS.attr('number'),
  emballage: DS.attr(),
  kms: DS.attr('string'),
  energie: DS.attr('string'),
  matieres_grasses_indic: DS.attr('string'),
  matieres_grasses: DS.attr('number'),
  matieres_grasses_saturees_indic: DS.attr('string'),
  matieres_grasses_saturees: DS.attr('number'),
  sucres_indic: DS.attr('string'),
  glucides: DS.attr('number'),
  glucides_dont_sucres: DS.attr('number'),
  fibres: DS.attr('number'),
  proteines: DS.attr('number'),
  sel_indic: DS.attr('string'),
  sel: DS.attr('number'),
  acteurs: DS.hasMany('acteur'),
  intrants: DS.hasMany('intrant')
});

Produit.reopenClass({
  FIXTURES: [
    { 
      id: 1,
      photo_url: 'assets/img/paindemiebiocasinocroppedall.jpg',
      marque: 'Cosina',
      denomination: 'Pain de mie',
      description: 'Grâce à ses grandes tranches moelleuses et savoureuses, ce pain de mie fabriqué dans le respect de l\'agriculture biologique vous accompagnera agréablement dans tous vos instants de consommation',
      origine_macro: 'Monde',
      conditionnement: 500,
      unite_conditionnement:'g',
      unite_nutrition:'g',
      prix_conditionnement:2.98,
      prix_global: 5.96,
      unite_globale: 'kg',
      prix_portion: 0.21,
      energie_portion: 105,
      kms: '20500.5',
      transparence: 75,
      nombre_portions: 14,
      unite_portion: 'tranche',
      matieres_grasses: 2.1,
      matieres_grasses_saturees: 0.2,
      glucides : 18,
      glucides_dont_sucres: 2 ,
      fibres : 1.2,
      proteines: 2.9 ,
      sel : 0.5 
    },
    { 
      id: 2,
      photo_url: 'assets/img/batavia.jpg',
      variete: 'Laitue batavia',
      denomination: 'Batavia',
      description: 'Elle est craquante et tendre, dotée d\'une grosse pomme vert clair ou vert jaune, gaufrée, avec les bords découpés, au goût légèrement sucré. Certaines variétés sont parfois rougeâtres. Il convient de la choisir avec une base bien blanche, signe de fraîcheur.La batavia se consomme crue, cuite ou braisée. Elle s\'associe agréablement avec les fines herbes, les œufs, le saumon fumé ou l\'oseille.',
      origine_macro: 'France',
      echelle: 'Nationale',
      unite_conditionnement:'pièce',
      prix_conditionnement:1.05,
      prix_producteur:0.65,
      distributeur:"La Vie Claire",
      lieu_vente:"Gerland",
      kms: '591',
      transparence: 85,
      categorie: "Fruits & Légumes",
      distance: 2,
      transports: "Camion",
      circuit: "Long",
      mode_culture: "Bio",
      mode_recolte: "Mécanique",
      acteurs: [1, 2, 3],
      intrants: [1, 2]
    },
    { 
      id: 3,
      photo_url: 'assets/img/oeufs.jpg',
      marque: 'La Vie Claire',
      variete: 'Calibre Gros, compris entre 63 g et 73 g',
      denomination: '6 œufs bio extra-frais',
      description: 'Les œufs La Vie Claire sont issus de poules élevées en plein air dans la Drôme et en Ardèche. Ces dernières sont nourries à base de céréales bio.',
      origine_macro: 'France',
      echelle: 'Régionale (Rhône-Alpes)',
      unite_conditionnement:'6 œufs',
      prix_conditionnement:2.75,
      prix_producteur:1.5,
      distributeur:"La Vie Claire",
      lieu_vente:"Gerland",
      emballage:[
        {
          element: "Boite", matiere: "Carton", "recyclable": true
        }
      ],
      kms: '121',
      transparence: 90,
      categorie: "Crêmerie et œufs",
      distance: 2,
      transports: "Camion",
      circuit: "Court",
      mode_culture: "Bio",
      mode_recolte: "Manuel",
      acteurs: [4,5,3],
      prix_portion: 0.46,
      energie_portion: 96.56,
      nombre_portions: 6,
      unite_portion: "œuf",
      unite_nutrition: "g",
      conditionnement: 408,
      matieres_grasses_indic: "list-group-item-warning",
      matieres_grasses: 6.73,
      matieres_grasses_saturees: 1.77,
      matieres_grasses_saturees_indic: "list-group-item-warning",
      glucides : 0.54,
      sucres_indic : "list-group-item-success",
      glucides_dont_sucres: 0.52 ,
      fibres : 1.2,
      proteines: 8.57 ,
      sel : 0.20,
      sel_indic : "list-group-item-warning"
    }
  ]
});

export default Produit;